### ISSUE TITLE
TAB compatibility

### ISSUE THREAD

**Issue by PSYCHEER** [imskeptical/DisplayTags#2]
Hey there! I've found your plugin on my way to get back what TAB took away from me and that's "unlimited" nametags.

I've found some issues with TAB compatibility plugin

![Image](https://github.com/user-attachments/assets/de6b46f0-2583-4e44-84f8-0a30ca1c9568)
When TAB is not hiding nametags, your plugin does it some weird, sometimes yes, sometimes not.
When TAB hides nametags, your plugin sometimes doesn't show nametag.

![Image](https://github.com/user-attachments/assets/bb3f42e0-ad67-459d-a725-38de2de42d7e)

![Image](https://github.com/user-attachments/assets/7fce5b73-d1a1-40ad-b3ce-c4ac89df1f99)

Please, can be this fixed?

**Comment by imskeptical** [comment]
This is a little strange, do you mind sharing me your current DisplayTags configuration & TAB configuration?

**Comment by PSYCHEER** [comment]
Sure, hopefully it's all

```yaml "DisplayTags
# ---------------------------------- #
#         DisplayTags Config         #
# ---------------------------------- #
# This is the configuration file for DisplayTags.
# To apply any changes you make here, run: /displaytags reload
# Wiki: https://github.com/imskeptical/DisplayTags/wiki

nametags:
  # Enable the nametags.
  # Set this to false if you want the vanilla player nametags shown instead.
  enabled: true

  # Should players see their own nametag?
  # Set to true to show your own nametag above your head (in first-person view).
  # Set to false to hide it.
  show-self: true

  # How often nametags should update (in seconds).
  # Lower = more frequent updates = more accurate, but slightly more CPU usage.
  # Recommended: 1 second
  update-interval: 1

  # How far away other players must be to see someone's nametag (in blocks).
  # Example: 32 = players can see nametags from up to 32 blocks away.
  visibility-distance: 32

  # Nametag Text Display Properties
  display:
    # The lines of text shown on the nametag, top to bottom.
    # Supports MiniMessage formatting: https://webui.advntr.dev/
    # PlaceholderAPI is supported for dynamic data.
    #
    # Built-in placeholders (no extra plugin needed):
    # {player}  - Player's name
    # {health}  - Player's current health (e.g. 20)
    lines:
      - "%vault_prefix%{player}"

    # Enable text shadow for the text display of a nametag.
    # Available values: true, false
    text-shadow: false

    # Should the text display of nametags be see through?
    # Available values: true, false
    see-through: false

    # The text alignment of the nametag's text display.
    # Available values: left, right, center
    text-alignment: "center"

    # The background color of the nametag's text display.
    # Use a hex color (like "#FFFFFF" for white), or "transparent" for no background.
    # Available values (excluding hex colors): default, transparent
    background: "transparent"

    # The billboard of the nametag's display.
    # Available values: fixed, vertical, horizontal, center
    billboard: "center"

    # The scale of the nametag's display.
    # This can be used to change the size of the nametag.
    scale:
      x: 1
      y: 1
      z: 1
```

```yaml "TAB, only this as others are disabled completely"
header-footer:
  enabled: true
  header:
  - '%img_logo% '
  - ''
  - ''
  - ''
  - ''
  - ''
  - <#FFAA00>&m                                                </#AA0000>
  - ''
  footer:
  - ''
  - '<#FFAA00>&lPÚTNICI</#AA0000>&4&l: %online% &7| <#AA0000>&lŠĽACHTA</#FFAA00>&6&l:
    %staffonline%'
  - ''
  - <#FFAA00>&m                                                </#AA0000>
  per-world: {}
  disable-condition: '%world%=disabledworld|%server%=disabledserver'
tablist-name-formatting:
  enabled: true
  disable-condition: '%world%=disabledworld|%server%=disabledserver'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: true
  sorting-types:
  - GROUPS:majitel,dozorca,mod,helper,architekt,bronz,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld|%server%=disabledserver'
```

**Comment by imskeptical** [comment]
(I'm assuming this IS what you did, but just try exactly as this) Set `invisible-nametags` in `scoreboard-teams:` to false, then, restart the server instead of just reloading the plugins.

**Comment by PSYCHEER** [comment]
That's the issue!
When it's on false then both are visible
When it's on true, sometimes it hides yours

**Comment by imskeptical** [comment]
Both should not be visible. Did you already set to false & restart the server? (as a reminder, not reloading the plugin configs, restarting it)

**Comment by PSYCHEER** [comment]
Yes, I'm restarting them all day long xD But for calm of your soul, I can do it again <3

**Comment by PSYCHEER** [comment]
![Image](https://github.com/user-attachments/assets/087ec492-8273-4dcf-b03d-27f272e07d27)

**Comment by imskeptical** [comment]
Ah sorry- I completely misinterpreted it somehow, I did mean keep it as true, I apologise!
Now, previously when I tested DisplayTags with TAB it seemed fine having invisible-nametags to true.
So, very sorry I just did that but to clarify, you have set `invisible-nametags` to true (got it right lol) and restarted the server before already?

**Comment by PSYCHEER** [comment]
![Image](https://github.com/user-attachments/assets/0deb5cba-d914-47fc-93a6-a23153443471)
Working on it

**Comment by imskeptical** [comment]
PacketEvents v2.9.0? Hmm, a little strange request, but can you maybe downgrade to PacketEvents v2.8.0? DisplayTags internally uses that version. It also relies on PacketEvents to hide vanilla nametags. You can try this IF the current method I presented does not work 😄

**Comment by PSYCHEER** [comment]
Oh sorry :D

![Image](https://github.com/user-attachments/assets/0f83ef85-0fdc-4f78-b959-31151369c808)
Have been testing a bit as it has a dependency :D but will try too

**Comment by imskeptical** [comment]
It's fine, I should be having DisplayTags support newer versions of it too soon enough.

**Comment by PSYCHEER** [comment]
![Image](https://github.com/user-attachments/assets/bf6f677c-486c-49df-bb8e-c357d7fbab36)

On other server I have problem I have duplicated nametags, without any plugin xDD Maybe it's related to? 🤔 
![Image](https://github.com/user-attachments/assets/b1c39cd7-69ca-4870-afc6-ff343266a1ce)

Still issue
![Image](https://github.com/user-attachments/assets/a0f458b0-e409-460d-923d-7f056908e378)

**Comment by imskeptical** [comment]
Without any plugins? How come...
Also, is that the TAB nametag being shown?

**Comment by PSYCHEER** [comment]
On this one I have NO plugin

Also the TAB nametag is not shown, one of two from DT

**Comment by imskeptical** [comment]
A little confused, what is the issue now then, is it not fixed? Unless you mean to fix issues with the other server which has no plugins.

**Comment by PSYCHEER** [comment]
The other server was just fun fact, sorry for confusion

When player rejoin onto server, TAB hides others nametag

**Comment by imskeptical** [comment]
TAB hides the DisplayTags' nametag?

**Comment by PSYCHEER** [comment]
> TAB hides the DisplayTags' nametag?

Clearly it looks so

**Comment by PSYCHEER** [comment]
It just doesn't show any nametag

**Comment by imskeptical** [comment]
Can you reload DisplayTags one time?

**Comment by PSYCHEER** [comment]
Then it brings them up

**Comment by imskeptical** [comment]
I see, any logs when player joins?

**Comment by PSYCHEER** [comment]
Only DB update

**Comment by imskeptical** [comment]
Alright, going to attempt to add a fix integrating TAB into the plugin. If TAB is detected & configured to hide nametags, DisplayTags won't attempt to hide nametags itself. Give me a little bit.

**Comment by PSYCHEER** [comment]
And maybe just a suggestion, do not message if is plugin up to date on join :D is annoying

**Comment by imskeptical** [comment]
Oh yeah, an option to disable this will be introduced in one of the upcoming versions, update checker was just rushed and made quickly 😓

**Comment by imskeptical** [comment]
What server version & software are you running?

**Comment by PSYCHEER** [comment]
Purpur 1.21.4

**Comment by imskeptical** [comment]
On a Paper 1.21.4 server, I am not able to replicate this issue at all. This may be an issue with Purpur in some way...? Sorry, I haven't explicitly stated support for Purpur as of yet for DisplayTags, but I'll keep looking for a fix, I'll update you soon if there is one.

**Comment by imskeptical** [comment]
Workaround implemented for 1.0.5, please try, reloading TAB plugin kinda breaks it so, reload DisplayTags to fix it again when you reload TAB!

**Comment by PSYCHEER** [comment]
Will provide more tests results tommorow in here.

**Comment by imskeptical** [comment]
Hey, haven't published v1.0.5 as it errored while deploying, I'll have it out today, sorry about that. You should also be safe to restore PacketEvents' version (to 2.9.0-...) once you have DT V1.0.5 too!

**Comment by PSYCHEER** [comment]
I'm at home already, waiting then O:)

**Comment by imskeptical** [comment]
Version deployed! Take a look here: https://modrinth.com/plugin/displaytags/version/VLLdJ9sb

**Comment by PSYCHEER** [comment]
Going to test, hopefully it will work :D

**Comment by PSYCHEER** [comment]
![Image](https://github.com/user-attachments/assets/07bc2835-41a1-403c-b874-4caff4feca22)

![Image](https://github.com/user-attachments/assets/1f5465aa-737f-4d71-9b23-5f8b71042e94)

No other plugin editing nametags...
When I go outside of range (default: 32) and then back it pop up back... but when I rejoin with one, the other has no nametag...still...

TAB = invisible-nametags: true
No error/warning or informational message in console.

![Image](https://github.com/user-attachments/assets/8b9c47ea-4c03-4ec5-82e0-f55a16f4a5bf)

Maybe can you add some packet debug loggin system to find out why's doing this?

**Comment by imskeptical** [comment]
I can't really understand the screenshots, all look the same.
Is DisplayTags' nametags not even working at all?
I tested this with TAB on a Purpur 1.21.4 server yesterday and it went perfectly fine.

**Comment by PSYCHEER** [comment]
My setup
Proxy > HUB > Server
TAB is on HUB & Server
When all players join first time, nametags are shown
When some player rejoin and players are in range, nametags of OTHERS are not shown.
In screenshots are two clients with different minecraft accounts (online-mode) and you can see on one is nametag visible, on another is not... that's what I rejoin with one

**Comment by imskeptical** [comment]
Which server is DisplayTags in, and which server are you testing/showing these screenshots from?

**Comment by PSYCHEER** [comment]
Server is the one I have DisplayTags in and from this server those screenshots are

https://youtu.be/41A-FkkG4Jo uploading video, wait a bit

**Comment by imskeptical** [comment]
I am assuming some config updates have been made.
Please show your current DisplayTags configuration.

**Comment by PSYCHEER** [comment]
```yaml
# ---------------------------------- #
#         DisplayTags Config         #
# ---------------------------------- #
# This is the configuration file for DisplayTags.
# To apply any changes you make here, run: /displaytags reload
# Wiki: https://github.com/imskeptical/DisplayTags/wiki

nametags:
  # Enable the nametags.
  # Set this to false if you want the vanilla player nametags shown instead.
  enabled: true

  # Should players see their own nametag?
  # Set to true to show your own nametag above your head (in first-person view).
  # Set to false to hide it.
  show-self: false

  # How often nametags should update (in seconds).
  # Lower = more frequent updates = more accurate, but slightly more CPU usage.
  # Recommended: 1 second
  update-interval: 1

  # How far away other players must be to see someone's nametag (in blocks).
  # Example: 32 = players can see nametags from up to 32 blocks away.
  visibility-distance: 32

  # Nametag Text Display Properties
  display:
    # The lines of text shown on the nametag, top to bottom.
    # Supports MiniMessage formatting: https://webui.advntr.dev/
    # PlaceholderAPI is supported for dynamic data.
    #
    # Built-in placeholders (no extra plugin needed):
    # {player}  - Player's name
    # {health}  - Player's current health (e.g. 20)
    lines:
      - "%vault_prefix%{player}"

    # Enable text shadow for the text display of a nametag.
    # Available values: true, false
    text-shadow: false

    # Should the text display of nametags be see through?
    # Available values: true, false
    see-through: false

    # The text alignment of the nametag's text display.
    # Available values: left, right, center
    text-alignment: "center"

    # The background color of the nametag's text display.
    # Use a hex color (like "#FFFFFF" for white), or "transparent" for no background.
    # Available values (excluding hex colors): default, transparent
    background: "transparent"

    # The billboard of the nametag's display.
    # Available values: fixed, vertical, horizontal, center
    billboard: "center"

    # The scale of the nametag's display.
    # This can be used to change the size of the nametag.
    scale:
      x: 1
      y: 1
      z: 1
```
